# Generated by Django 4.2.7 on 2023-12-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_orderitem_order_orderitem_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session_id',
        ),
    ]
