# Generated by Django 4.2.7 on 2023-12-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_order_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='session_id',
            field=models.CharField(max_length=32),
        ),
    ]
