# Generated by Django 4.2.7 on 2023-12-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_orderitem_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='currency',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
